### ISSUE TITLE
Allele count

### ISSUE THREAD

**Issue by PabloRomanjo** [KarchinLab/open-cravat-readthedocs#2]
Hi! First of all thank you very much for the tool, I use it a lot!

I have a question, is it possible to obtain in the annotation process the allele count of variants in a reference population (e.g., gnomad)?

Thank you in advance 😉

![uLsU7te2](https://user-images.githubusercontent.com/93191947/164716302-abff0623-6c3d-41eb-977c-46be095390b2.png)

**Comment by mryaninsilico** [comment]
Pablo,

 

Really glad you like Open CRAVAT and are getting good use from it.

 

Just to make sure I understand, there are currently 7 or so population frequency annotators in Open CRAVAT.  For example gnomAD and gnomAD3 provide allele frequency by population.  Are you asking for counts instead of or in addition to frequency?

 

Thanks,

 

Michael Ryan, PhD

In Silico Solutions

From: Pablo Román ***@***.***> 
Sent: Friday, April 22, 2022 8:42 AM
To: KarchinLab/open-cravat-readthedocs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [KarchinLab/open-cravat-readthedocs] Allele count (Issue #2)

 

Hi! First of all thank you very much for the tool, I use it a lot!

I have a question, is it possible to obtain in the annotation process the allele count of variants in a reference population (e.g., gnomad)?

Thank you in advance 😉

 <https://user-images.githubusercontent.com/93191947/164716302-abff0623-6c3d-41eb-977c-46be095390b2.png>

**Comment by PabloRomanjo** [comment]
Michael, 

Thank you very much for your quick answer. I was asking about the possibility of obtaining the allele count during the annotation process. It would not matter whether instead of or in addition to the allele frequency.

Thank you again!

**Comment by mryaninsilico** [comment]
Thanks.  We will put your request in and let you know when we get an updated annotator if it is possible.

 

Mike

**Comment by kmoad** [comment]
The `gnomad3_counts` annotator provides this.
